name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token <<< "${{ secrets.DATABRICKS_HOST }}\n${{ secrets.DATABRICKS_TOKEN }}"

    - name: Deploy Notebook to Databricks
      env:
        DATABRICKS_WORKSPACE_DIR: '/Workspace/YourProject'
        NOTEBOOK_PATH: 'path/to/your/notebook.py'
      run: |
        databricks workspace mkdirs $DATABRICKS_WORKSPACE_DIR
        databricks workspace import $NOTEBOOK_PATH $DATABRICKS_WORKSPACE_DIR/notebook.py -l PYTHON
