name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Databricks CLI
      run: |
        python -m pip install --upgrade pip
        pip install databricks-cli

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
        echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config

    - name: Deploy Notebook to Databricks
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_WORKSPACE_DIR: '/Workspace/KrgProject'
        NOTEBOOK_PATH: 'Notebook/sample-1.ipynb'
      run: |
        databricks workspace mkdirs $DATABRICKS_WORKSPACE_DIR
        databricks workspace import $NOTEBOOK_PATH $DATABRICKS_WORKSPACE_DIR/sample-1.ipynb -l PYTHON
